import React, { ChangeEvent, ChangeEventHandler, useEffect } from 'react';
import Head from 'next/head';
import { useState } from 'react';
import DropdownComponent from "../components/Dropdown/DropdownComponent";

export default function Home() {
	const [value, setValue] = useState('');
	const [num, setNum] = useState(1)

	const [data, setData] = useState('');
	const getData = async () => {
		const response = await fetch(`/api/quote?name=${value}&number=${num}`);
		const resData = await response.json();
		console.log(resData);
		setData(resData.sentences);
	};

	useEffect(() => {
		getData();
	}, []);

	return (
		<>
			<Head>
				<title>Random Quote Generator</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex flex-col justify-center items-center">
				{/* code starts here */}
				<h1 className="py-10 text-center">Random Quote Generator!</h1>
				<p className="text-lg">Number of People: </p>

				{/* dropdown */}
				<DropdownComponent num={num} setNum={setNum}></DropdownComponent>
				<form className="p-4">
					<textarea
						className="border-2 border-black resize"
						rows={4}
						onChange={(event: ChangeEvent<HTMLTextAreaElement>) =>
							setValue(event.target.value)
						}
					></textarea>
				</form>

				{/* button */}
				<button
					onClick={() => {
						console.log('value:', value);
						getData();
					}}
					className="bg-gray-300 border-2 border-black resize-none"
				>
					Submit
				</button>

				{/* quotes */}
				<div dangerouslySetInnerHTML={{ __html: data }} />
			</main>
		</>
	);
}
