import React, { ChangeEvent, useEffect, useState } from 'react';
import Head from 'next/head';
import { toast, ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Button from '../components/Button';
import DropdownComponent from '../components/Dropdown/DropdownComponent';
import Modal from '../components/Modal';

export default function Home() {
	const [value, setValue] = useState('');
	const [num, setNum] = useState(1);
	let [isOpen, setIsOpen] = useState(false)

	var parse = require('html-react-parser');

	const [data, setData] = useState('');
	const getData = async () => {
		// const response = await fetch(
		// 	`/api/quote?number=${num}&name=${value.replaceAll('\n', ',')}`,
		// 	{
		// 		method: 'GET',
		// 		mode: 'cors',
		// 		headers: { 'Content-Type': 'application/json' },
		// 	}
		// );
		const response = await fetch(
			`http://localhost:8080/api/v1/generate-quote?number_of_people=${num}&names=${value.replaceAll(
				'\n',
				','
			)}`,
			{
				method: 'GET',
				mode: 'cors',
				headers: { 'Content-Type': 'application/json' },
			}
		);
		const resData = await response.json();
		if (!response.ok) {
			toast.error('Error: ' + resData.error);
		} else {
			setData(resData.data.sentences);
		}
	};

	useEffect(() => {
		// getData();
	}, []);

  function openModal() {
    setIsOpen(true)
  }

	return (
		<>
			<Head>
				<title>Random Quote Generator</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex flex-col justify-center items-center">
				{/* code starts here */}
				<h1 className="py-10 text-center">Random Quote Generator!</h1>

				{/* help modal*/}
				<Modal isOpen={isOpen} setIsOpen={setIsOpen} />
				<button onClick={openModal}>help</button>

				{/* input field */}
				<div className="flex justify-center items-center">
					<p className="text-lg pr-3">Number of People: </p>

					{/* dropdown */}
					<DropdownComponent num={num} setNum={setNum}></DropdownComponent>
				</div>

				<form className="p-4">
					<textarea
						className="border-2 border-black resize rounded"
						rows={4}
						onChange={(event: ChangeEvent<HTMLTextAreaElement>) =>
							setValue(event.target.value)
						}
						placeholder="Your favorite names..."
					></textarea>
				</form>

				{/* execute button */}
				<div className="flex flex-col sm:block">
					<Button text="Generate Quote" value={value} getData={getData} />
					<Button text="Shuffle Names" value={value} getData={getData} />
				</div>

				<ToastContainer autoClose={2000} />

				{/* quotes */}
				<div className="py-4 px-4 text-left sm:w-[600px] ">{parse(data)}</div>

				<div className="py-4 px-4 text-center text-sm">Made for Kowan</div>
			</main>
		</>
	);
}
